### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by austerus** [jmstriegel/php.googleplusapi#4]
Hello,

As far as I can see, this is less of an actual API and more of a method of extracting data from GooglePlus streams and profiles. There's no way to post, authenticate or work with an authenticated user. Still, it's more than what Google offeres.

My issue is that in its current form the business logic (which should only relate to extracting the data) is mixed not only with the data model but also with the database-related functionality as well. It would be much nicer to have separate classes: those used to represent data, those used to extract/parse/export data from GooglePlus and those that map them to db objects and read/write them to db.

Regards

**Comment by jmstriegel** [comment]
Hi austerus.

That's correct, this is a read-only library that gives you access to public posts and follower/followees.

Regarding the structure, I'm hoping to separate out a core library that handles fetches from the G+ servers. A second set of classes would be related to persisting data to a mysql cache.

This version was a quick effort at getting something working for an experiment I was working on. I expected an official API to be available at this point, but based on feedback and usage, I'll be continuing development until a public API becomes available, and I'll try and incorporate some of these requests as soon as I can.
