### ISSUE TITLE
Are there any plans on adding a posting API?

### ISSUE THREAD

**Issue by freak4pc** [jmstriegel/php.googleplusapi#5]
I mean an API to add a new post to the user's Google+ profile, 
Are there any plans on doing anything like that?

Shai.

**Comment by jmstriegel** [comment]
Hi freak4pc,

At this point, I'm going to just focus on improving access to publicly available data. Authentication and write-level behaviors will probably have to wait until the official API becomes available.

On the other hand, if you've spent any time reverse engineering the authentication/posting process and have any hints as to how to make it happen, let me know -- I'd be happy to reconsider. I haven't devoted a lot of effort to researching this yet.

**Comment by freak4pc** [comment]
Thank you :) Appreciate your answer. 
If i'll have time to do some sniffing i'll keep you updated.

Cheers.

**Comment by rutwick** [comment]
Yes indeed... we need a 'post'ing API! The official API too does 'get' only...
