### ISSUE TITLE
Coder API Library

### ISSUE THREAD

**Issue by kwang1321** [jmstriegel/php.googleplusapi#8]
I am new to using Coder on Raspberry Pi and would appreciate some pointers.
Where can I find API library for peripherals e.g. UART, I2C, SPI?
How do I stream data to from browser to Pi server?
How do I steam data from Pi sever to browser?

Thanks

**Comment by jmstriegel** [comment]
Check out the spi, i2c and websockets examples in apps/tests. That should
have what you need to get started.

**Comment by kwang1321** [comment]
Jason,

Thanks for the reply. I am teaching my students to design a IOT.  We use
Arduino and XBee for the wireless data communication. Could you give me
some pointers on how to connect Raspberry Pi server to Arduino using the
serial port on coder?

Thanks

Karl

---

Dr. Karl L. Wang
Director of Technology
Professor of Electrical and Computer Engineering
International Technological University (www.itu.edu)
355 W. San Fernando St.
San Jose, CA 95113
(408)204-6832
